"""add cascade delete for tutor-courses

Revision ID: fe000f35f1c4
Revises: 8e2d8616bbc7
Create Date: 2026-05-05 01:13:02.522052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe000f35f1c4'
down_revision: Union[str, Sequence[str], None] = '8e2d8616bbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_tutor_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'tutors', ['tutor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_tutor_id_fkey'), 'courses', 'tutors', ['tutor_id'], ['id'])
    # ### end Alembic commands ###
